### PR TITLE
compatible with v2.1.2 Admin:- Locales, Currencies, Exchange Rates, I…

### PR DESCRIPTION
**Pull request by Anmol-Chauhan**
…nventory Sources, Channels, Users, Roles, Admin Login, Logout has been completed

### CODE REVIEW

**Comment by imanbahmani** [comment]
please confirm this pull request for version 2.1.2

**Comment by imanbahmani** [comment]
please confirm this pull request for version 2.1.2

**Comment by Anmol-Chauhan** [comment]
@imanbahmani, Yes, this PR request for v2.1.2 but the work is in progress, not completed yet.

**Comment by imanbahmani** [comment]
When will the new version be uploaded?

**Comment by Anmol-Chauhan** [comment]
@imanbahmani, The team is working on it and we will release the latest version soon, thanks for your patience.

**Comment by Anmol-Chauhan** [comment]
New PR Raised on behalf of this:- https://github.com/bagisto/headless-ecommerce/pull/253
So I am closing this PR and the work is in progress for the latest version of Bagisto v2.2.1

**Pull request closed without merging**
